
package com.quantiguous.services;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DomesticRemittanceByPartnerService", targetNamespace = "http://www.quantiguous.com/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DomesticRemittanceByPartnerService {


    /**
     * 
     * @param beneficiaryAccountNo
     * @param remitterToBeneficiaryInfo
     * @param remitterAddress
     * @param remitterIFSC
     * @param partnerCode
     * @param transactionStatus
     * @param transferAmount
     * @param remitterName
     * @param beneficiaryAddress
     * @param uniqueResponseNo
     * @param version
     * @param requestReferenceNo
     * @param beneficiaryIFSC
     * @param debitAccountNo
     * @param uniqueRequestNo
     * @param beneficiaryName
     * @param customerID
     * @param beneficiaryContact
     * @param transferType
     * @param attemptNo
     * @param transferCurrencyCode
     * @param remitterContact
     * @param remitterAccountNo
     * @param lowBalanceAlert
     */
    @WebMethod(action = "http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/remit")
    @RequestWrapper(localName = "remit", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.Remit")
    @ResponseWrapper(localName = "remitResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.RemitResponse")
    public void remit(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<String> version,
        @WebParam(name = "uniqueRequestNo", targetNamespace = "http://www.quantiguous.com/services")
        String uniqueRequestNo,
        @WebParam(name = "partnerCode", targetNamespace = "http://www.quantiguous.com/services")
        String partnerCode,
        @WebParam(name = "customerID", targetNamespace = "http://www.quantiguous.com/services")
        String customerID,
        @WebParam(name = "debitAccountNo", targetNamespace = "http://www.quantiguous.com/services")
        String debitAccountNo,
        @WebParam(name = "remitterAccountNo", targetNamespace = "http://www.quantiguous.com/services")
        String remitterAccountNo,
        @WebParam(name = "remitterIFSC", targetNamespace = "http://www.quantiguous.com/services")
        String remitterIFSC,
        @WebParam(name = "remitterName", targetNamespace = "http://www.quantiguous.com/services")
        String remitterName,
        @WebParam(name = "remitterAddress", targetNamespace = "http://www.quantiguous.com/services")
        AddressType remitterAddress,
        @WebParam(name = "remitterContact", targetNamespace = "http://www.quantiguous.com/services")
        ContactType remitterContact,
        @WebParam(name = "beneficiaryName", targetNamespace = "http://www.quantiguous.com/services")
        String beneficiaryName,
        @WebParam(name = "beneficiaryAddress", targetNamespace = "http://www.quantiguous.com/services")
        AddressType beneficiaryAddress,
        @WebParam(name = "beneficiaryContact", targetNamespace = "http://www.quantiguous.com/services")
        ContactType beneficiaryContact,
        @WebParam(name = "beneficiaryAccountNo", targetNamespace = "http://www.quantiguous.com/services")
        String beneficiaryAccountNo,
        @WebParam(name = "beneficiaryIFSC", targetNamespace = "http://www.quantiguous.com/services")
        String beneficiaryIFSC,
        @WebParam(name = "transferType", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<TransferTypeType> transferType,
        @WebParam(name = "transferCurrencyCode", targetNamespace = "http://www.quantiguous.com/services")
        CurrencyCodeType transferCurrencyCode,
        @WebParam(name = "transferAmount", targetNamespace = "http://www.quantiguous.com/services")
        BigDecimal transferAmount,
        @WebParam(name = "remitterToBeneficiaryInfo", targetNamespace = "http://www.quantiguous.com/services")
        String remitterToBeneficiaryInfo,
        @WebParam(name = "uniqueResponseNo", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<String> uniqueResponseNo,
        @WebParam(name = "attemptNo", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigInteger> attemptNo,
        @WebParam(name = "requestReferenceNo", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<String> requestReferenceNo,
        @WebParam(name = "lowBalanceAlert", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<Boolean> lowBalanceAlert,
        @WebParam(name = "transactionStatus", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransactionStatusType> transactionStatus);

    /**
     * 
     * @param accountCurrencyCode
     * @param partnerCode
     * @param accountNo
     * @param accountBalanceAmount
     * @param customerID
     * @param version
     * @param lowBalanceAlert
     */
    @WebMethod(action = "http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getBalance")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetBalanceResponse")
    public void getBalance(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<String> version,
        @WebParam(name = "partnerCode", targetNamespace = "http://www.quantiguous.com/services")
        String partnerCode,
        @WebParam(name = "customerID", targetNamespace = "http://www.quantiguous.com/services")
        String customerID,
        @WebParam(name = "accountNo", targetNamespace = "http://www.quantiguous.com/services")
        String accountNo,
        @WebParam(name = "accountCurrencyCode", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<CurrencyCodeType> accountCurrencyCode,
        @WebParam(name = "accountBalanceAmount", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigDecimal> accountBalanceAmount,
        @WebParam(name = "lowBalanceAlert", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<Boolean> lowBalanceAlert);

    /**
     * 
     * @param reqTransferType
     * @param partnerCode
     * @param transactionStatus
     * @param transferAmount
     * @param transferType
     * @param transactionDate
     * @param version
     * @param transferCurrencyCode
     * @param requestReferenceNo
     */
    @WebMethod(action = "http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getRemittanceStatus")
    @RequestWrapper(localName = "getRemittanceStatus", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetRemittanceStatus")
    @ResponseWrapper(localName = "getRemittanceStatusResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetRemittanceStatusResponse")
    public void getRemittanceStatus(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<String> version,
        @WebParam(name = "partnerCode", targetNamespace = "http://www.quantiguous.com/services")
        String partnerCode,
        @WebParam(name = "requestReferenceNo", targetNamespace = "http://www.quantiguous.com/services")
        String requestReferenceNo,
        @WebParam(name = "transferType", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransferTypeType> transferType,
        @WebParam(name = "reqTransferType", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransferTypeType> reqTransferType,
        @WebParam(name = "transactionDate", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<XMLGregorianCalendar> transactionDate,
        @WebParam(name = "transferAmount", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigDecimal> transferAmount,
        @WebParam(name = "transferCurrencyCode", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<CurrencyCodeType> transferCurrencyCode,
        @WebParam(name = "transactionStatus", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransactionStatusType> transactionStatus);

    /**
     * 
     * @param numDebits
     * @param partnerCode
     * @param dateRange
     * @param accountNo
     * @param customerID
     * @param closingBalance
     * @param numTransactions
     * @param numCredits
     * @param version
     * @param openingBalance
     * @param transactionsArray
     */
    @WebMethod(action = "http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getTransactions")
    @RequestWrapper(localName = "getTransactions", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetTransactions")
    @ResponseWrapper(localName = "getTransactionsResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetTransactionsResponse")
    public void getTransactions(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<String> version,
        @WebParam(name = "partnerCode", targetNamespace = "http://www.quantiguous.com/services")
        String partnerCode,
        @WebParam(name = "customerID", targetNamespace = "http://www.quantiguous.com/services")
        String customerID,
        @WebParam(name = "accountNo", targetNamespace = "http://www.quantiguous.com/services")
        String accountNo,
        @WebParam(name = "dateRange", targetNamespace = "http://www.quantiguous.com/services")
        DateRangeType dateRange,
        @WebParam(name = "openingBalance", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigDecimal> openingBalance,
        @WebParam(name = "numDebits", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigInteger> numDebits,
        @WebParam(name = "numCredits", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigInteger> numCredits,
        @WebParam(name = "closingBalance", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigDecimal> closingBalance,
        @WebParam(name = "numTransactions", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigInteger> numTransactions,
        @WebParam(name = "transactionsArray", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransactionsArrayType> transactionsArray);

}
